# Numpy 学习笔记

首先载入numpy

In [2]:
import numpy as np

## array 的创建
- 从list
- numpy专用的函数
- 从文件

### 从list创建array

In [3]:
A1 = np.array([1,2,3,4])

In [4]:
A2 = np.array([[1,2],[3,4]])

In [5]:
type(A1),type(A2)

(numpy.ndarray, numpy.ndarray)

下面分别为array的维度、元素个数和元素的数据类型，必须知道的是array的数据类型都是一致的，这也是和list不同之处，当然也可以通过astype对array的dtype进行修改

In [14]:
A1.shape,A1.size,A1.dtype

((4L,), 4, dtype('int32'))

In [15]:
A2.shape,A2.size,A2.dtype

((2L, 2L), 4, dtype('int32'))

修改dtype

In [19]:
A1 = A1.astype(float)

In [20]:
A1.shape,A1.size,A1.dtype

((4L,), 4, dtype('float64'))

如果只是A1.astype(float)，只会产生一个copy，不会改变原有的array，所以需要A1 = A1.astype(float)

### 利用numpy内部函数创建array

In [22]:
# 创建范围
x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# 使用linspace，两个端点被列入
np.linspace(0, 10, 25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [28]:
np.logspace(0, 10, 10, base=10)
#这是log

array([  1.00000000e+00,   1.29154967e+01,   1.66810054e+02,
         2.15443469e+03,   2.78255940e+04,   3.59381366e+05,
         4.64158883e+06,   5.99484250e+07,   7.74263683e+08,
         1.00000000e+10])

In [29]:
x, y = np.mgrid[0:5, 0:5] # 类似于在MATLAB中meshgrid


In [30]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [31]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

如何创建随机数也是重要的课题

In [43]:
# 均匀随机数 [0,1]
np.random.rand(5,5)

array([[ 0.627362  ,  0.34139954,  0.6523623 ,  0.33321993,  0.76896548],
       [ 0.59282786,  0.81559008,  0.00236589,  0.69561897,  0.37296083],
       [ 0.51419723,  0.94928824,  0.48353059,  0.8642235 ,  0.46276642],
       [ 0.13405895,  0.40543813,  0.54588491,  0.34611549,  0.37717105],
       [ 0.9318832 ,  0.62219423,  0.64938416,  0.74601187,  0.98445164]])

In [33]:
# 标准正态分布的随机数
np.random.randn(5,5)

array([[ 2.4403    , -0.4198038 , -0.94809562,  0.22236567, -1.37220116],
       [ 1.91422623,  1.5177614 ,  0.20183929, -0.27903303,  0.47215714],
       [-1.54593249, -0.37837963,  0.88670743,  0.42138127, -0.86748744],
       [-0.31187616, -0.83962355,  0.53324723, -0.60049717,  1.51453462],
       [-0.6414476 ,  0.5802475 , -0.58636885,  0.82250405, -0.28596525]])

In [34]:
#对角矩阵
np.diag([1,2,1])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [36]:
# 对角线与来自主对角线的偏移
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [41]:
#全零和全一矩阵
np.ones([3,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [38]:
np.zeros([4,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

注意的是numpy产生array的zeros和randn入口参数不同，randn中入口参数不需要对ndimension进行list化或者tuple化，而zeros需要进行list化，详见下面参考

In [44]:
np.random.rand?

In [45]:
np.ones?

## 读取文件